name: Deploy to production

on:
  release:
    types: [published]

env:
  APP_PROFILE: prod

jobs:
  get-image-tag:
    if: startsWith(github.event.release.tag_name, 'api/')
    name: Generate Image Tag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ env.APP_PROFILE }}-${{ steps.vars.outputs.sha_short }}
      release_version: "${{ steps.get_version.outputs.release_version }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get image tag
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get the version
        id: get_version
        run: |
          echo "::set-output name=release_version::${GITHUB_REF#refs/tags/api/}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: get-image-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: echo variables
        id: echo_variables
        run: |
          echo ${{ needs.get-image-tag.outputs.image_tag }}
          echo ${{ needs.get-image-tag.outputs.release_version }}
